application: otse-elust
version: 1
runtime: python
api_version: 1

handlers:

- url: /media
  static_dir: static/media

- url: /manage.*
  script: main.py
  login: required

- url: .*
  script: main.py
